sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 12345678
  alioss:
    endpoint: oss-cn-shanghai.aliyuncs.com
    access-key-id: LTAI5t8Napq3cf5KAV6gysjV
    access-key-secret: 88u7SMF0ldvxWLoJ5wmNIXdkN9COeB
    bucket-name: sky-jimcast
  redis:
    host: localhost
    port: 6379
  wechat:
    appid: wx8aca2abfda15d3e6
    secret: fe31f4c986ecaaa1e3e1643792ec03cc
    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: D:\pay\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\pay\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://6619cf50.r6.cpolar.top/notify/paySuccess
    refundNotifyUrl: https://6619cf50.r6.cpolar.top/notify/refundSuccess
  shop:
    address: 上海市静安区万航渡路50弄
  baidu:
    ak: UEBQm9c3KZ5Lrs02C2q